import type {BlogPost} from "./types";
import {Lead,H2,P,Ul,Li,Callout,TextLink} from "@/components/blog/Prose";
function Body(){return <><Lead>A good-looking dorm is also a room you can use. Start with the furniture that determines how you move through the space, then add the details. Dormscape's Pro 3D studio lets you test that arrangement alongside the same 2D floor plan.</Lead>
<H2>Check the outline before the styling</H2><P>Confirm the room's width and length. Record where the door, windows, and fixed closets actually sit. The studio only shows openings that are in the plan; an empty wall does not mean your real room has no door there. Use Room to add or correct openings, and enter a measured ceiling height if you have one.</P><P>For an alcove or L-shaped room, use <TextLink href="/plan/draw">2D drawing</TextLink> with Plus or Pro, or the Pro <TextLink href="/plan/draw/3d">3D Room Builder</TextLink> before generating the layout. An accurate outline gives both views the same useful starting point.</P>
<H2>Arrange the largest pieces first</H2><Ul><Li>Select the bed in Arrange, try its position, then rotate it if another orientation makes more sense.</Li><Li>Place the desk where you can use the chair comfortably. Check the space behind the chair as well as the desktop.</Li><Li>Keep fixed furniture anchored. Lock movable pieces once you are happy with them so another drag does not shift them by accident.</Li><Li>Add smaller pieces after the main arrangement works. Hide an item to compare the room with and without it.</Li></Ul>
<H2>Use 2D for position, 3D for perspective</H2><P>The Top camera is useful for a quick floor-level comparison. The 2D plan makes precise footprints easier to inspect. Room gives an angled overview, and Inside lets you look around from eye level. Switching among them does not create a separate design or spend a generation credit.</P><P>If a drag is hard to judge, select the item and open Position &amp; measurements. Enter its X and Y position in feet, or update its width, depth, and height from actual measurements. Undo lets you reverse an experiment. On mobile, choose Move selected before dragging the piece.</P>
<H2>Keep desktop accessories with their surface</H2><P>For eligible small objects, Place on a surface attaches the piece to a larger desk, shelf, dresser, or bed. An attached accessory follows its supporting furniture when that furniture moves or rotates. Use Floor / free placement to detach it, or enter a measured height above the floor when needed.</P>
<H2>Look for conflicts, then check the real room</H2><P>Open Room, then View &amp; layout options and Placement checks. The studio can flag overlaps, wall boundaries, ceiling height, and proximity to an inward door swing. A warning is a prompt to look closer. It is not a guarantee of fit or an accessibility assessment. Confirm clearances with your room measurements and residence hall requirements.</P>
<H2>Finish with light, color, and a saved version</H2><P>Use Style to compare finishes and lighting after the arrangement works. These previews leave your shopping list and prices unchanged. Shop shows actual product photos and links. Save a named design when you find a layout you like, then export a PNG or share a link for feedback.</P><Callout label="Try the workflow"><p><TextLink href="/pricing#pro">Pro includes 3D room building and planning</TextLink>, 10 plan credits, and custom vibes. <TextLink href="/plan">Open your planner</TextLink> and start with the bed, desk, and walking space before decorating.</p></Callout></>;}
const post:BlogPost={slug:"arrange-a-dorm-room-in-3d",title:"How to arrange your dorm room in 3D",description:"A practical workflow for furniture placement, measurements, camera views, and saved layouts in Dormscape's Pro 3D room planner.",excerpt:"Start with the bed and desk, check the space around them, then add finishes. A calmer way to plan in 3D.",date:"2026-09-15",updated:"2026-09-24",readingTimeMin:4,faqTopic:"Arranging in 3D",faqs:[
{q:"How do I move furniture in the 3D planner on a phone?",a:"Select an item from Arrange or the room, then choose Move selected. Drag the piece to its new position. Use the position fields for precise placement, or Undo to reverse a move."},
{q:"Do the 2D and 3D layouts stay synchronized?",a:"Yes. They use the same furniture positions and room outline. A move or rotation in one view appears in the other. Switching views does not generate a new design."},
{q:"Does changing a floor finish or lighting change my shopping list?",a:"No. Room finishes, preview colors, and lighting are visualization settings. Shop retains your selected products and prices; product swaps are a separate action."},
{q:"Can I use an L-shaped room in 3D?",a:"Yes. Draw your room's outline first, then generate the plan. Pro can view and arrange that same outline in 3D. Confirm the real wall and furniture measurements before relying on the preview."}
],Body};export default post;
