import type { BlogPost } from "./types";
import { Lead,H2,P,Ol,Li,Callout,TextLink } from "@/components/blog/Prose";
import { BUILDER_FAQS } from "@/content/builder-faq";
function Body(){return <>
  <Lead>Your room does not have to start with a catalog floor plan. Dormscape's 3D Room Builder lets you start with a blank grid, build your actual outline, and take that same room into the furniture planner. The builder is included with Pro.</Lead>
  <H2>Start with the floor, or start with the walls</H2><P>Open <TextLink href="/plan/draw/3d">Build in 3D</TextLink> from the Draw section. Sign in with a Pro account, then choose Start building in 3D. You can place a rectangular floor by clicking two opposite corners, or enter its length and width in feet. Walls rise around that floor automatically.</P><P>For an L-shaped room or an alcove, try a starting shape. If the outline is different, choose Trace new walls and click the corners in order. Close the outline to create the floor. The grid snaps to your chosen increment, and the coordinate fields let you enter more precise positions.</P>
  <H2>Refine the shape before adding furniture</H2><Ol><Li><strong>Select a corner:</strong> drag its blue handle on the grid, or enter its X and Z coordinates. The floor and connected walls follow the new position.</Li><Li><strong>Select a wall:</strong> check its length and split it at the midpoint to add another bend. You can then move the new corner to form a recess.</Li><Li><strong>Use Undo:</strong> a completed edit can be reversed. Redo is available until you make another edit. Replacing the footprint is also undoable during this editing session.</Li></Ol><P>Walls must form one valid outline. Crossing walls, overlapping openings, and edits that leave an opening hanging outside its wall are rejected with an explanation. Those checks help keep the room usable in both planner views.</P>
  <H2>Put doors and windows where they really are</H2><P>Choose Door or Window, set its width, and click a clear wall. A preview shows the intended position before you place it. You can also add an opening using the wall selector. Select the opening afterward to set its width, distance from the wall's start, and wall number. Door controls cycle through four hinge and swing orientations.</P><P>Measure from a consistent corner in the real room. A door near a desk is very different from a door on the opposite wall, even when the overall room dimensions are the same. The furniture planner carries these positions through and can flag potential door-clearance conflicts.</P>
  <H2>Reserve space for built-in closets</H2><P>Choose Closet after enclosing the room. Enter its width and depth, then click the floor to place it. Top view makes it easier to position the footprint against a wall. Select the closet to drag it, change its measurements, rotate the footprint, or remove it. Coordinate fields are available for precise placement without dragging.</P><P>Closets must fit inside the room and cannot overlap each other. They transfer into both planner views as fixed storage. Furniture that overlaps this space is flagged, so you can adjust the arrangement.</P>
  <H2>Choose the room details, then furnish it</H2><P>Room details holds ceiling height, floor finish, wall color, occupancy, and mattress size. Finishes are preview choices. They do not buy flooring or add paint to your shopping list. Enter your real ceiling height if you have it; the initial value is a starting point.</P><P>Choose Style &amp; plan validates your room, then takes you to the existing style and budget step. Generate the design there, and the planner opens in 3D with your drawn walls, floor, doors, windows, and closets. The 2D view uses the same outline and furniture positions.</P>
  <Callout label="Included with Pro"><p>Pro includes 3D room building, live 3D planning, custom vibes, 10 plan credits, and everything in Plus. Drawing the room shell does not use a generation credit. Compare <TextLink href="/pricing#pro">Pro features</TextLink> or <TextLink href="/plan/draw/3d">start your room</TextLink>.</p></Callout>
  <H2>Know where your draft lives</H2><P>The unfinished builder draft stays in this browser on this device, associated with your signed-in account. It is not a cloud backup. After furnishing the room, use Save design in the planner to keep a named copy in your account. Clearing site storage can remove an unfinished draft.</P><P>The builder models a single connected floor on one level. It does not create internal partitions, holes in the floor, separate apartments, or multiple stories. Its preview supports planning; verify measurements and housing rules before making purchases or physical changes.</P>
</>;}
const post:BlogPost={slug:"build-a-dorm-room-in-3d",title:"Build your dorm room from the ground up in 3D",metaTitle:"3D Dorm Room Builder: Walls, Floors, Doors and Windows",description:"Build your actual dorm room in 3D with Dormscape Pro. Shape walls, add doors, windows, and closets, then open your drawn room in the furniture planner.",excerpt:"From a blank grid to your own furnished room. A practical guide to the new Pro 3D Room Builder.",date:"2026-09-24",readingTimeMin:4,faqTopic:"3D Room Builder",faqs:BUILDER_FAQS,Body};
export default post;
