import type {BlogPost} from "./types";
import {Lead,H2,P,Ol,Li,Callout,TextLink} from "@/components/blog/Prose";
function Body(){return <><Lead>Dormscape's 3D Room Studio is here. It is included with Pro and turns your room plan into a space you can arrange and explore. Start from the same school dimensions or drawn outline, then switch between 2D and 3D without rebuilding the room.</Lead>
<H2>Start with the room you actually have</H2><P>Choose your school and room, draw an outline in 2D, or start with a blank grid in the Pro <TextLink href="/plan/draw/3d">3D Room Builder</TextLink>. Place a floor, shape the walls, and add doors and windows. Pick your vibe and budget as usual. Rooms built in 3D open in the 3D planner automatically. Free, Flex, and Plus keep the 2D editor, and the 3D button explains the Pro upgrade before changing anything.</P>
<H2>Four tools, one workspace</H2><Ol><Li><strong>Arrange:</strong> select furniture in the room or inventory. Move it, rotate it, or hide it. Expand Position &amp; measurements only when you need precise numbers.</Li><Li><strong>Room:</strong> check dimensions, add doors and windows, and enter your measured ceiling height. View &amp; layout options hold wall visibility, placement checks, and reset.</Li><Li><strong>Style:</strong> try floor finishes, a wall preview color, and daylight or evening lighting. These are visual choices, not changes to the products in your cart.</Li><Li><strong>Shop:</strong> review the real product photos, prices, swaps, and shopping links alongside the layout.</Li></Ol>
<H2>See the space from a useful angle</H2><P>Room gives you an angled overview. Top helps you judge where furniture sits on the floor. Inside places the camera at eye level so you can look around from a fixed point. Inside is a viewing preset, not a walking simulator. Drag empty space to orbit in the room view, and scroll, pinch, or use the zoom controls to look closer.</P><P>On a phone, select a piece and choose Move selected before dragging furniture. That keeps a camera gesture from accidentally rearranging your room. Undo reverses a completed move, and both views use the same furniture positions.</P>
<H2>Keep the plan, not just a screenshot</H2><P>Save design keeps a named copy in your account, including the room's 3D settings. Share can create a room link or export the current view as a PNG. Anyone with a shared link can see its 2D plan; interactive 3D requires Pro. Sharing a link does not create a live multiplayer editing session.</P><Callout label="Included with Pro"><p>Switching between 2D and 3D uses no extra generation credits. Pro includes 3D Room Builder, live 3D Room Studio, unlimited room plans, custom vibes, and everything in Plus. See <TextLink href="/pricing#pro">current Pro pricing</TextLink>, then <TextLink href="/plan">open the planner</TextLink>.</p></Callout>
<H2>What the preview can and cannot tell you</H2><P>The 3D furniture is an approximate model, not an exact digital replica of an Amazon product. Product photos show the selected items. Unmeasured heights use defaults, so enter real measurements before relying on clearances. Placement checks flag possible conflicts; they do not certify a layout. If your browser cannot render 3D, your room remains editable in 2D.</P></>;}
const post:BlogPost={slug:"introducing-dormscape-3d-room-studio",title:"Meet Dormscape's live 3D Room Studio",description:"Explore the new Pro 3D dorm planner: arrange furniture, try finishes, switch views, and save your room before move-in.",excerpt:"Your floor plan has a new perspective. Meet the live 3D studio included with Dormscape Pro.",date:"2026-09-15",updated:"2026-09-24",readingTimeMin:3,faqTopic:"3D Room Studio",faqs:[
{q:"Is Dormscape's 3D room planner available now?",a:"Yes. Live 3D Room Studio is available with Dormscape Pro. Open a room plan and choose 3D room. Free, Flex, and Plus include the 2D editor; interactive 3D requires Pro."},
{q:"Does switching to 3D use a plan credit?",a:"No. Switching views does not generate another design or use a plan credit. Both views use the same furniture layout. Pro includes unlimited room plans."},
{q:"Can my roommate see my shared 3D room?",a:"Anyone with the room link can view its 2D plan. A viewer with Pro can also explore it in 3D. Shared links are not live collaborative editing sessions."},
{q:"Are the 3D furniture models exact product replicas?",a:"No. Models represent approximate furniture shapes and dimensions. Check the selected product's photos and actual measurements before buying. Room heights and furniture heights may use defaults until you enter measured values."},
{q:"What happens if my browser does not support 3D?",a:"The studio offers Open 2D plan if WebGL is unavailable or interrupted. Your existing room layout remains editable in 2D. You can retry 3D on a supported browser."}
],Body};export default post;
