import type { BlogPost } from "./types";
import { Lead, H2, P, Ol, Li, Callout, TextLink } from "@/components/blog/Prose";
function Body() { return <>
  <Lead>A shared room works better when the layout and shopping decisions stay together. Dormscape starts with your room and a shoppable plan, then gives that plan a home in My rooms.</Lead>
  <H2>Start with a useful plan</H2><P>Choose your school, hall, and room, then select a style and budget. If your room is not listed, enter your measurements. Plus includes 2D drawing; Pro adds the 3D room builder. The planner keeps the product list beside the room so you can arrange furniture, swap products, and follow the shopping total.</P>
  <H2>Move the plan into a workspace</H2><P>Choose Open workspace below your completed planner. Your furniture positions, room outline, openings, and shopping selections carry over. Opening the workspace does not generate another design or use a credit. Existing saved designs also appear in <TextLink href="/rooms">My rooms</TextLink>, where you can open them as workspaces.</P>
  <H2>Invite your roommates</H2><Ol><Li>The room owner opens Invite roommates. Pro includes one active shared room with up to four people, including the owner.</Li><Li>Enter your roommate's email address, choose editing or comment access, and send the invitation. They receive an email with a Join the room button.</Li><Li>Your friends sign in with the verified email address you invited and join free. An editing invitation lets them adjust the shared room and shopping list. Comment access lets them explore and give feedback.</Li></Ol><P>Invitations reserve a place for seven days. Sending again to the same email replaces only that person's earlier invitation. Cancel a pending invitation to free its place. People who already joined keep access until the owner removes them in Roommates.</P>
  <H2>Keep the shopping list central</H2><P>The Room section keeps product picks beside the layout. Shopping adds an overview of who is bringing each item and whether it is already owned, supplied by the school, or still needs buying. An ownership assignment is a planning note, not a payment request. Confirm shared purchases together before checkout.</P>
  <H2>Know who is planning with you</H2><P>The shared room shows which roommates are online or away and whether they are arranging the room or browsing the shopping list. Named cursors help you point out a spot in the plan, even when you use different zoom levels or one person switches to 3D. When Room voice is available, join to listen or turn on your microphone to talk through the choices. Voice is optional, with mute and leave controls.</P>
  <H2>Give feedback where it belongs</H2><P>Open Comments from any workspace tab. Attach a note to the room, a piece of furniture, a product, or a kept layout alternative. Furniture notes appear as pins in the plan. Reply in the same thread and resolve it after making a decision; resolved conversations stay available for later. Workspace comments are private to room members. They are separate from public saved-design review links.</P>
  <H2>Protect the version everyone agreed on</H2><P>Name important versions before trying a new idea. Dormscape retains the latest 20 versions. Restoring one changes the room and shopping state for everyone and keeps a copy of the state you replaced. Connected roommates receive saved changes through live updates, with periodic refresh as a fallback. If two editors save conflicting changes, the app asks you to review the latest version or keep your edits in a personal copy.</P>
  <Callout label="One room, clear permissions"><p>A Pro host unlocks collaboration and 3D access inside that shared room. Guests do not receive Pro in their personal rooms and cannot spend the host's generation credits. <TextLink href="/pricing#pro">Compare Pro features</TextLink>.</p></Callout>
  <H2>Keep a room personal whenever you want</H2><P>The owner can make a shared room personal, which removes invited members and invalidates invitation links. Their layout and shopping list stay saved. Personal rooms work just as well for a student planning alone.</P>
</>; }
const post: BlogPost = { slug: "plan-a-dorm-room-with-roommates", title: "Plan your dorm room with roommates, from layout to shopping list", description: "Keep your dorm layout, shared shopping list, and roommate feedback together in Dormscape My rooms. Learn about invitations, roles, and saved versions.", excerpt: "A shared plan for your room, your purchases, and the people you live with.", date: "2026-09-27", readingTimeMin: 4, faqTopic: "My rooms and roommates", faqs: [
  { q: "What is the difference between the planner and a workspace?", a: "The planner creates a room layout and shoppable product list from your room, style, and budget. A workspace keeps that room as an ongoing project with a furniture library, layout alternatives, shopping assignments, and version history. My rooms is where your saved designs and workspaces live." },
  { q: "Do all roommates need to purchase Pro?", a: "No. One Pro owner can host one active shared workspace with up to four people, including the owner. Invited friends join free with editing or comment access. The host's Pro access applies only inside that shared room." },
  { q: "Does sharing a room spend a design credit?", a: "No. Generation uses design credits. Saving, manual edits, switching views, and invitations use no credits. Guests cannot spend the room owner's generation credits." },
  { q: "Are workspace invitations private?", a: "Workspaces require sign-in and membership. Invitations are emailed and tied to that recipient's verified email address. Each pending invitation reserves one of four places for seven days. The owner can cancel it at any time. A forwarded link cannot be used by another account." },
  { q: "Can I see my roommate's cursor?", a: "Yes. A Pro host's shared workspace shows online and away status and named cursors in the room. Room cursors follow the same floor location across different zoom levels and 2D or 3D views. Live presence requires an active connection." },
  { q: "Can we comment on a piece of furniture?", a: "Yes. Select it and choose Comment on selected. Open conversations appear as pins on the piece. Roommates can reply, resolve their own threads and revisit resolved notes. Owners and editors can also resolve other threads. You can comment on products, the whole room and kept layouts too." },
  { q: "Do I need to use a microphone to collaborate?", a: "No. Live cursors and comments work without voice. When Room voice is available, you can join to listen with your microphone off. Turning it on requires your explicit action and browser permission. You can mute or leave at any time. Dormscape does not record or transcribe the call." },
  { q: "What happens if two roommates edit at the same time?", a: "Live updates notify connected roommates when a change is saved, with periodic refresh as a fallback. Each save checks the current room version. If someone saved a newer version, your edits are not silently written over theirs. You can keep your changes in a personal copy or load the latest shared room. Simultaneous edits are not automatically merged." },
], Body };
export default post;
