import type { BlogPost } from "./types";
import { Lead,H2,P,Ol,Li,Callout,TextLink } from "@/components/blog/Prose";
function Body(){return <>
  <Lead>A room can be 14 feet long and 12 feet wide without giving you a usable 14-by-12-foot rectangle. An alcove, an angled wall, or an entrance recess changes where furniture fits. Building that outline first gives you a more useful starting point.</Lead>
  <H2>Measure the outline in order</H2><P>Start at one corner and work around the room in a consistent direction. Record each wall length and the position of every change in direction. Measure the width of doors and windows, plus the distance from a nearby corner to the start of each opening. Check your school's published floor plan when available, and confirm dimensions in the room if you can.</P><P>Do not treat a starting shape in the builder as verified information. Its dimensions exist to help you begin. If your measurements are estimates, keep that uncertainty in mind when comparing tight clearances.</P>
  <H2>Choose the simplest useful construction method</H2><Ol><Li><strong>A rectangle with a small recess:</strong> start with a rectangle, select a wall, and split it to create extra corners. Move those corners to describe the recess.</Li><Li><strong>An L-shaped footprint:</strong> use the L-shaped starter, then select its corners and enter your measured positions.</Li><Li><strong>An angled or unusual outline:</strong> trace the perimeter corner by corner. Angled walls are supported. Close the walls to fill the floor, then inspect the result from the top view.</Li></Ol><P>Dormscape's grid uses feet. X and Z describe the floor position; ceiling height is a separate setting. Grid snapping helps you work quickly, while the numeric fields let you refine each corner.</P>
  <H2>Add openings before judging the layout</H2><P>Place doors and windows before you move into furniture planning. Set each opening's width and wall offset. Check the door's hinge and swing orientation instead of accepting the first default. If you shorten a wall until an opening no longer fits, the builder asks you to correct it rather than silently discarding the opening.</P><P>The builder supports one connected room, with up to 40 corners and 20 openings. It does not model interior partition walls, separate rooms, floor holes, or stairs. Represent only a footprint the tool can accurately carry into the planner.</P>
  <H2>Review from above, then from an angle</H2><P>Use Top view to check the outline and opening positions. Switch to 3D view to review the enclosure and height. Cutaway walls let you see the interior without deleting the walls themselves. Undo and redo make it easier to compare an edit before committing to a shape.</P><P>When the room is ready, choose your style and budget. The furnished design opens in the 3D Room Studio. Check its layout in both 2D and 3D, adjust furniture as needed, and compare product measurements before buying. A model or placement check does not guarantee that an item will fit.</P>
  <Callout label="Build the room you have"><p>The <TextLink href="/plan/draw/3d">3D Room Builder</TextLink> is included with Pro. Plus and Pro also include <TextLink href="/plan/draw">2D drawing</TextLink>. See the <TextLink href="/blog/build-a-dorm-room-in-3d">full builder walkthrough</TextLink> for the controls and the handoff into the planner.</p></Callout>
</>;}
const post:BlogPost={slug:"plan-an-irregular-dorm-room-in-3d",title:"How to plan an L-shaped or irregular dorm room in 3D",description:"Measure an irregular dorm room, trace angled walls and alcoves, add openings, and carry your custom room into Dormscape's Pro 3D planner.",excerpt:"Alcoves, angled walls, and awkward corners: build a footprint that reflects the room you actually have.",date:"2026-09-24",readingTimeMin:3,faqTopic:"Irregular rooms",faqs:[
  {q:"Can the 3D Room Builder handle angled walls and L-shaped dorm rooms?",a:"Yes. Trace the perimeter corner by corner, or start with an L-shaped room and move its corners. Angled walls and alcoves are supported as part of one closed, non-crossing outline."},
  {q:"What happens when I shorten a wall containing a door or window?",a:"The builder checks that every opening still fits on its wall and does not overlap another opening. If the change would break that fit, the edit is rejected. Move, resize, or remove the opening first, then change the wall."},
  {q:"Can I use exact measurements instead of dragging corners?",a:"Yes. Select a corner in the room or Room elements list and enter its X and Z position in feet. Openings have wall, width, and distance-from-wall-start fields. You can enter a rectangular floor's length and width directly too."},
],Body};export default post;
