import type { BlogPost } from "./types";
import { Lead, H2, P, Ol, Li, TextLink } from "@/components/blog/Prose";
function Body() { return <>
  <Lead>Two mini fridges and no trash can is an avoidable move-in problem. Start with one shopping list, then agree on who brings each shared item.</Lead>
  <H2>Check what your school already provides</H2><P>Look at your housing information for beds, desks, wardrobes, and other supplied furniture. Measure your actual room and check appliance rules. A room model is useful for planning, but it cannot confirm a specific room's measurements or authorize equipment your housing office restricts.</P>
  <H2>Build the list alongside your layout</H2><P>In <TextLink href="/plan">Dormscape's planner</TextLink>, your shopping list sits beside the room. Select a style, set a budget, and review bedding, lighting, storage, and decor. Swap an item when a different choice suits you better. Product dimensions may be incomplete or approximate; verify the seller's selected variant before buying.</P>
  <H2>Give every item a clear status</H2><Ol><Li><strong>To buy:</strong> keep the product in the purchasing estimate.</Li><Li><strong>Already have:</strong> retain it in the room plan while taking it out of the amount still to buy.</Li><Li><strong>School provides:</strong> record supplied items so you do not budget for them again.</Li></Ol><P>In a workspace's Shopping section, assign an item to a roommate or leave it Shared. Assignments help coordinate decisions. They do not split a payment, track reimbursements, or prove an order was placed.</P>
  <H2>Agree before checkout</H2><P>Use comments on a product to discuss size, color, and price. Give one person responsibility for each shared purchase. Prices and stock can change, so confirm the final details at the retailer. Dormscape's affiliate links may earn a commission at no extra cost to you.</P>
  <H2>Keep the list with the room</H2><P>Use Open workspace from your planner to keep the layout and product selections together in <TextLink href="/rooms">My rooms</TextLink>. Personal workspaces are available on every account. A Pro owner can invite up to seven friends into one shared room. Saving and organizing the list use no generation credits.</P>
</>; }
const post: BlogPost = { slug: "shared-dorm-shopping-list", title: "Make a shared dorm shopping list without buying everything twice", description: "Coordinate a college move-in with a shared dorm shopping list. Track school-provided items, assign purchases, and keep the list beside your room layout.", excerpt: "Know what you have, what you need, and who is bringing it.", date: "2026-09-27", readingTimeMin: 3, faqTopic: "Shared shopping", faqs: [
  { q: "Does marking an item as owned remove it from my room?", a: "No. Workspace ownership status keeps the item in the plan while excluding it from the amount still to buy. Removing a product from the shopping list is a separate action." },
  { q: "Does Dormscape collect or split roommate payments?", a: "No. Shopping assignments are planning notes. Roommates agree on payments themselves, and purchases happen at the retailer." },
  { q: "Can I use My rooms without roommates?", a: "Yes. Personal workspaces are private and available on every account. You can keep layouts and shopping lists together without inviting anyone." },
], Body };
export default post;
