/** Visible landing answers and structured data deliberately share one source. */
export const BUILDER_FAQS=[
  {q:"Can I draw my own dorm room in 3D?",a:"Yes. Dormscape Pro includes the 3D Room Builder. Place a rectangular floor, start from a room shape, or trace a custom closed wall outline on a 3D grid. Adjust corners, add doors, windows, and closets, then choose a vibe and budget to furnish that same room in the 3D planner."},
  {q:"Is 3D room drawing included with Plus?",a:"No. Drawing directly in 3D is a Pro feature. Plus and Pro both include the existing 2D drawing tool. Only Pro includes the 3D Room Builder and interactive 3D Room Studio."},
  {q:"What room shapes can I build?",a:"Build a single connected, single-level room with a closed outline, including rectangles, L-shapes, alcoves, and angled walls. The builder supports up to 40 corners, 20 doors or windows, and 20 closets, within a 60 by 60 foot grid. Separate rooms, internal partition walls, floor holes, and multiple stories are not supported."},
  {q:"Will my doors, windows, and measurements transfer into the planner?",a:"Yes. The room outline, opening positions and widths, door swings, closet footprints, ceiling height, floor finish, wall color, occupancy, and mattress size carry into the planner. Choose a style and budget next. Your furnished design opens in 3D and can also be viewed in 2D."},
  {q:"Can I add a closet when drawing my room in 3D?",a:"Yes. After making your floor and walls, choose Closet, set its width and depth, and click inside the room. Select a closet to drag it, edit exact measurements, rotate its footprint, or remove it. Closets carry into both planner views as fixed storage, where overlapping furniture is flagged. You can also place and edit closets with coordinate fields."},
  {q:"Does building a room use a design credit?",a:"No. Drawing and editing the room shell do not generate a furnished design or consume credits. The builder requires Pro, which includes 10 plan credits."},
  {q:"Where is my unfinished 3D room saved?",a:"An unfinished builder draft is kept in this browser on this device, separately for your signed-in account. It is not a cloud save or a cross-device backup. After furnishing the room, use Save design in the planner to keep a named design in your account. Clearing browser storage can remove an unfinished draft."},
  {q:"Are the construction preview and measurements guaranteed?",a:"No. Enter measurements from your real room. Default room shapes, ceiling heights, and openings are starting points, not verified building data. The preview is a planning aid, not an architectural drawing, building-permit document, or guarantee of furniture clearance."},
];
