"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { builderBounds, builderError, builderOutline, emptyDraft, moveBuilderCorner, parseBuilderDraft, pathError, placeBuilderOpening, presetDraft, removeBuilderCorner, roomArea, snapPoint, splitBuilderWall, type BuilderDraft, type BuilderSelection, type BuilderTool } from "@/lib/room-builder";
import { openingAtPoint, roomEditError } from "@/lib/room-editing";
import { FLOOR_FINISHES } from "@/lib/studio";
import type { Point, WallOpening } from "@/lib/types";
import BrandLoader from "@/components/site/BrandLoader";
import s from "./Builder.module.css";

type History={past:BuilderDraft[];now:BuilderDraft;future:BuilderDraft[]};
type SceneState={draft:BuilderDraft;tool:BuilderTool;selection:BuilderSelection;snap:number;cutaway:boolean;anchor:Point|null};
type View={update:(state:SceneState)=>void;fit:(view?:"room"|"top")=>void;zoom:(factor:number)=>void;destroy:()=>void};
type SceneOptions={onSelect:(s:BuilderSelection)=>void;onPoint:(p:Point)=>void;onMoveCorner:(i:number,p:Point)=>void;onMoveOpening:(i:number,p:Point)=>void;onCancel:()=>void;onError:(m:string)=>void;previewOpening:(target:number|WallOpening["kind"],p:Point)=>WallOpening|null};
const TOOLS:[BuilderTool,string,string][]=[["select","↖","Select"],["floor","▱","Floor"],["wall","⌑","Walls"],["door","↳","Door"],["window","⊞","Window"],["orbit","⟳","Orbit"]];
const BED_SIZES=["twin_xl","twin","full","full_xl","queen"] as const;
const ft=(n:number)=>Number(n.toFixed(2));
function coordinates(form:HTMLFormElement):Point {const data=new FormData(form);return {x:Number(data.get("x")),y:Number(data.get("y"))};}

export default function RoomBuilder({userId,onComplete}:{userId:string;onComplete:(draft:BuilderDraft)=>Promise<void>}){
  const [history,setHistory]=useState<History>({past:[],now:emptyDraft(),future:[]});const d=history.now;
  const [tool,setTool]=useState<BuilderTool>("floor"),[selection,setSelection]=useState<BuilderSelection>(null),[anchor,setAnchor]=useState<Point|null>(null);
  const [snap,setSnap]=useState(.5),[cutaway,setCutaway]=useState(true),[tab,setTab]=useState<"build"|"finish">("build"),[error,setError]=useState(""),[storageNote,setStorageNote]=useState(""),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false);
  const [replace,setReplace]=useState<"floor"|"wall"|"rectangle"|"l"|"alcove"|null>(null),[help,setHelp]=useState(false),[openingWidth,setOpeningWidth]=useState(3);
  const [sceneError,setSceneError]=useState(""),[ready,setReady]=useState(false),[retry,setRetry]=useState(0);
  const mount=useRef<HTMLDivElement>(null),view=useRef<View|null>(null),current=useRef<SceneOptions|null>(null),latest=useRef<SceneState|null>(null),controls=useRef<HTMLDivElement>(null);
  const key="dormscape-3d-draft-v1:"+userId;
  useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const saved=parseBuilderDraft(JSON.parse(raw));if(saved){setHistory({past:[],now:saved,future:[]});setTool(saved.closed?"select":"wall");setStorageNote("Draft restored from this device.");}else setStorageNote("The previous draft could not be restored. Start a new room below.");}}catch{setStorageNote("Device storage is unavailable. Keep this tab open while you build.");}setLoaded(true);},[key]);
  useEffect(()=>{if(!loaded)return;const timer=setTimeout(()=>{try{localStorage.setItem(key,JSON.stringify(d));setStorageNote("Draft kept on this device. Save the furnished design to your account later.");}catch{setStorageNote("Draft could not be kept on this device. Keep this tab open.");}},400);return()=>clearTimeout(timer);},[d,key,loaded]);
  // Undo may remove the floor or reopen the outline. Keep construction tools valid.
  useEffect(()=>{setTool(current=>{
    if((current==="door"||current==="window")&&!d.closed)return d.points.length?"wall":"floor";
    if(current==="wall"&&d.closed||current==="floor"&&d.points.length)return "select";
    return current;
  });},[d.closed,d.points.length]);
  function apply(next:BuilderDraft|string){if(typeof next==="string"){setError(next);return false;}setHistory(h=>({past:[...h.past,h.now].slice(-60),now:next,future:[]}));setError("");return true;}
  function undo(){setHistory(h=>h.past.length?{past:h.past.slice(0,-1),now:h.past.at(-1)!,future:[h.now,...h.future]}:h);setSelection(null);setAnchor(null);setError("");}
  function redo(){setHistory(h=>h.future.length?{past:[...h.past,h.now],now:h.future[0],future:h.future.slice(1)}:h);setSelection(null);setAnchor(null);setError("");}
  function closeWalls(){const next={...d,closed:true};const problem=builderError(next);if(apply(problem??next)){setTool("select");setSelection(null);}}
  function addPoint(p:Point){
    if(tool==="door"||tool==="window"){if(apply(placeBuilderOpening(d,tool,p,openingWidth))){setSelection({kind:"opening",index:d.openings.length});setTool("select");}return;}
    p=snapPoint(p,snap);
    if(tool==="floor"){
      if(d.points.length){setError("Use New floor to replace this footprint, or select a corner to edit it.");return;}
      if(!anchor){setAnchor(p);setError("");return;}
      const next={...d,points:[anchor,{x:p.x,y:anchor.y},p,{x:anchor.x,y:p.y}],closed:true};
      if(apply(builderError(next)??next)){setAnchor(null);setTool("select");setSelection(null);requestAnimationFrame(()=>view.current?.fit());}return;
    }
    if(tool==="wall"){
      if(d.closed){setError("The room is enclosed. Use Select to move a corner or split a wall.");return;}
      if(d.points.length>=3&&Math.hypot(p.x-d.points[0].x,p.y-d.points[0].y)<.35){closeWalls();return;}
      const next={...d,points:[...d.points,p]};apply(pathError(next.points)??next);
    }
  }
  function select(next:BuilderSelection){setSelection(next);setTab("build");setError("");}
  const state:SceneState={draft:d,tool,selection,snap,cutaway,anchor};latest.current=state;
  current.current={onSelect:select,onPoint:addPoint,onMoveCorner:(i,p)=>apply(moveBuilderCorner(d,i,p)),onMoveOpening:(i,p)=>{const o=d.openings[i];if(o)apply(placeBuilderOpening(d,o.kind,p,o.width_ft,i));},onCancel:()=>{setAnchor(null);setSelection(null);setTool("select");},onError:setSceneError,previewOpening:(target,p)=>{const o=typeof target==="number"?d.openings[target]:{kind:target,edge:0,offset_ft:0,width_ft:openingWidth};return d.closed&&o?openingAtPoint(builderOutline(d),o,p,typeof target==="number"?target:-1):null;}};
  useEffect(()=>{if(!loaded)return;let disposed=false;setReady(false);setSceneError("");
    (async()=>{try{const path="/experience/room-builder.js";const module=await import(/* webpackIgnore: true */ /* turbopackIgnore: true */ path) as {createBuilderScene:(node:HTMLElement,options:SceneOptions)=>View};if(disposed||!mount.current)return;
      const callbacks:SceneOptions={onSelect:s=>current.current!.onSelect(s),onPoint:p=>current.current!.onPoint(p),onMoveCorner:(i,p)=>current.current!.onMoveCorner(i,p),onMoveOpening:(i,p)=>current.current!.onMoveOpening(i,p),onCancel:()=>current.current!.onCancel(),onError:m=>{if(!disposed)setSceneError(m);},previewOpening:(k,p)=>current.current!.previewOpening(k,p)};
      view.current=module.createBuilderScene(mount.current,callbacks);view.current.update(latest.current!);setReady(true);
    }catch{if(!disposed)setSceneError("3D could not start in this browser. Your draft is safe. Retry, or use the coordinate and measurement controls to keep building.");}})();return()=>{disposed=true;view.current?.destroy();view.current=null;};
  },[loaded,retry]);
  useEffect(()=>{view.current?.update(state);});
  function chooseTool(next:BuilderTool){
    if(next==="floor"&&d.points.length){setReplace("floor");return;}
    setTool(next==="wall"&&d.closed?"select":next);setTab("build");setAnchor(null);setSelection(null);setError("");
    if(next==="door"||next==="window")setOpeningWidth(next==="door"?3:4);
  }
  function newShape(shape:NonNullable<typeof replace>){
    if(d.points.length&&!replace){setReplace(shape);return;}
    const next=shape==="wall"||shape==="floor"?emptyDraft():presetDraft(shape);
    apply({...next,settings:d.settings,occupants:d.occupants,bedSize:d.bedSize});setReplace(null);setAnchor(null);setSelection(null);setTool(shape==="wall"?"wall":shape==="floor"?"floor":"select");requestAnimationFrame(()=>view.current?.fit());
  }
  function patchOpening(index:number,patch:Partial<WallOpening>){const next={...d,openings:d.openings.map((o,i)=>i===index?{...o,...patch}:o)};apply(roomEditError(builderOutline(next))??next);}
  async function finish(){setError("");const problem=builderError(d);if(problem){setError(problem);return;}setBusy(true);try{try{localStorage.setItem(key,JSON.stringify(d));}catch{}await onComplete(d);}catch(e){setError(e instanceof Error?e.message:"Could not open the planner. Your draft is still here.");setBusy(false);}}
  const bounds=d.points.length?builderBounds(d.points):null,selectedCorner=selection?.kind==="corner"?d.points[selection.index]:null,selectedOpening=selection?.kind==="opening"?d.openings[selection.index]:null,wall=selection?.kind==="wall"?selection.index:null;
  const hint=tool==="floor"?(anchor?"Choose the opposite corner to place your floor.":"Click two corners on the grid to place a rectangular floor."):tool==="wall"?"Click to place wall corners. Click the first corner or Close walls to finish.":tool==="door"||tool==="window"?"Hover over a wall to preview, then click to place your "+tool+".":tool==="orbit"?"Drag to orbit. Scroll or pinch to zoom.":"Select a corner, wall, door, or window. Drag a corner to reshape the room.";
  return <div className={s.builder} data-testid="room-builder" onKeyDown={e=>{if((e.target as HTMLElement).closest("input,select,textarea"))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==="Escape"){setReplace(null);setAnchor(null);setSelection(null);}}}>
    <header className={s.builderHeader}><div><p className={s.eyebrow}>Dormscape / 3D Room Builder <span>PRO</span></p><h1>Make room for <em>your room.</em></h1></div><div className={s.headerActions}><Link href="/plan/draw">2D draw</Link><button onClick={()=>setHelp(h=>!h)} aria-expanded={help}>Quick guide</button></div></header>
    {help&&<div className={s.guide}><strong>Build in three moves.</strong><p>1. Place a floor or trace walls and close the outline. 2. Add doors and windows, then select them for exact measurements. 3. Choose your style and budget; your design opens in 3D.</p><p>Orbit mode moves the camera. Select mode moves corners or openings. Scroll or pinch to zoom. Undo reverses one completed edit. Prefer a keyboard? Use the coordinate forms and element list. All measurements are feet.</p><button onClick={()=>setHelp(false)}>Got it</button></div>}
    <div className={s.workspace}>
      <nav className={s.tools} aria-label="Construction tools"><div className={s.toolGroup}>{TOOLS.map(([id,icon,label])=><button key={id} aria-pressed={tool===id} disabled={(id==="door"||id==="window")&&!d.closed} onClick={()=>chooseTool(id)}><span aria-hidden="true">{icon}</span>{label}</button>)}</div>
        <div className={s.secondaryTools}><button disabled={!history.past.length} onClick={undo} aria-label="Undo last edit">↶<small>Undo</small></button><button disabled={!history.future.length} onClick={redo} aria-label="Redo last edit">↷<small>Redo</small></button></div>
        <div className={s.viewTools}><button onClick={()=>view.current?.fit("room")}>3D view</button><button onClick={()=>view.current?.fit("top")}>Top view</button><button onClick={()=>view.current?.fit()}>Fit room</button><div><button aria-label="Zoom out" onClick={()=>view.current?.zoom(1.18)}>−</button><button aria-label="Zoom in" onClick={()=>view.current?.zoom(.85)}>+</button></div></div>
      </nav>
      <section className={s.viewport} aria-label="Live 3D construction grid"><div className={s.viewportHeading}><span><i/> LIVE / {d.closed?"ROOM ENCLOSED":"CONSTRUCTION"}</span><span>{d.closed?ft(roomArea(d.points))+" sq ft":"60 × 60 ft grid"}</span></div>
        <div className={s.mount} ref={mount}/>
        {!ready&&!sceneError&&<div className={s.sceneMessage}><BrandLoader label="Opening the 3D grid…"/></div>}
        {sceneError&&<div className={s.sceneMessage} role="status"><strong>Your room is still here.</strong><p>{sceneError}</p><button onClick={()=>setRetry(n=>n+1)}>Retry 3D</button><button onClick={()=>controls.current?.querySelector<HTMLElement>("button,input")?.focus()}>Use numeric controls</button></div>}
        <div className={s.hint}><span className={s.toolBadge}>{tool.toUpperCase()}</span><p>{hint}</p></div>
      </section>
      <aside className={s.inspector} ref={controls} aria-label="Room building controls"><div className={s.inspectorTabs} role="group" aria-label="Room controls"><button aria-pressed={tab==="build"} onClick={()=>setTab("build")}>Build room</button><button aria-pressed={tab==="finish"} onClick={()=>setTab("finish")}>Room details</button></div>
        <div className={s.inspectorScroll}>
          {tab==="build"&&<>
            {!d.points.length&&<><p className={s.eyebrow}>01 / Start with space</p><h2>Your blank canvas.</h2><p className={s.muted}>Place a floor on the grid, trace your own walls, or start with a shape.</p><div className={s.presets}><button onClick={()=>newShape("rectangle")}><span>▭</span>Rectangle</button><button onClick={()=>newShape("l")}><span>⌞</span>L-shaped</button><button onClick={()=>newShape("alcove")}><span>⌑</span>Alcove</button></div></>}
            {tool==="floor"&&!d.points.length&&<form className={s.section} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),l=Number(f.get("length")),w=Number(f.get("width"));const next={...presetDraft("rectangle",l,w),settings:d.settings,occupants:d.occupants,bedSize:d.bedSize};if(apply(builderError(next)??next)){setAnchor(null);setTool("select");requestAnimationFrame(()=>view.current?.fit());}}}><h3>Or enter your floor size</h3><div className={s.fieldRow}><label>Length (ft)<input name="length" type="number" min="4" max="60" step=".25" defaultValue="14" required/></label><label>Width (ft)<input name="width" type="number" min="4" max="60" step=".25" defaultValue="12" required/></label></div><button className={s.secondary}>Place floor &amp; walls</button></form>}
            {tool==="wall"&&!d.closed&&<><div className={s.section}><h2>Trace your walls.</h2><p className={s.muted}>Each point adds a corner. Closing the walls creates the floor automatically.</p><CoordinateForm key={d.points.length} title="Add a corner by coordinates" point={{x:0,y:0}} onSubmit={addPoint} button="Add corner"/><button className={s.secondary} disabled={d.points.length<3} onClick={closeWalls}>Close walls &amp; create floor</button></div></>}
            {(tool==="door"||tool==="window")&&d.closed&&<div className={s.section}><p className={s.eyebrow}>02 / Add the details</p><h2>Place a {tool}.</h2><label className={s.field}>Width (ft)<input type="number" min=".5" max="12" step=".25" value={openingWidth} onChange={e=>setOpeningWidth(Math.max(.5,Math.min(12,Number(e.target.value)||.5)))}/></label><p className={s.muted}>Click a clear wall in the room, or choose one below. Openings cannot overlap.</p><form onSubmit={e=>{e.preventDefault();const edge=Number(new FormData(e.currentTarget).get("edge")),a=d.points[edge],b=d.points[(edge+1)%d.points.length];if(a&&b)addPoint({x:(a.x+b.x)/2,y:(a.y+b.y)/2});}}><label className={s.field}>Wall<select name="edge">{d.points.map((a,i)=>{const b=d.points[(i+1)%d.points.length];return <option key={i} value={i}>Wall {i+1} · {ft(Math.hypot(b.x-a.x,b.y-a.y))} ft</option>;})}</select></label><button className={s.secondary}>Add {tool} to wall</button></form></div>}
            {selectedCorner&&selection&&<div className={s.section}><p className={s.eyebrow}>Corner {selection.index+1}</p><h2>Shape the space.</h2><CoordinateForm key={selection.index+":"+selectedCorner.x+":"+selectedCorner.y} title="Exact corner position" point={selectedCorner} button="Apply position" onSubmit={p=>apply(moveBuilderCorner(d,selection.index,p))}/><button className={s.textDanger} onClick={()=>{if(apply(removeBuilderCorner(d,selection.index)))setSelection(null);}}>Remove this corner</button></div>}
            {wall!==null&&d.points[wall]&&<div className={s.section}><p className={s.eyebrow}>Wall {wall+1}</p><h2>{ft(Math.hypot(d.points[(wall+1)%d.points.length].x-d.points[wall].x,d.points[(wall+1)%d.points.length].y-d.points[wall].y))} ft long.</h2><p className={s.muted}>Select either corner to move it. Split this wall to create an alcove or another bend.</p><div className={s.buttonRow}><button onClick={()=>select({kind:"corner",index:wall})}>Start corner</button><button onClick={()=>select({kind:"corner",index:(wall+1)%d.points.length})}>End corner</button></div><button className={s.secondary} disabled={!d.closed} onClick={()=>{if(apply(splitBuilderWall(d,wall)))select({kind:"corner",index:wall+1});}}>Split wall at midpoint</button></div>}
            {selectedOpening&&selection&&<form key={JSON.stringify([selection,selectedOpening])} className={s.section} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);patchOpening(selection.index,{edge:Number(f.get("edge")),width_ft:Number(f.get("width")),offset_ft:Number(f.get("offset"))});}}><p className={s.eyebrow}>Selected {selectedOpening.kind}</p><h2>A little more precise.</h2><label className={s.field}>Wall<select name="edge" defaultValue={selectedOpening.edge}>{d.points.map((_,i)=><option value={i} key={i}>Wall {i+1}</option>)}</select></label><div className={s.fieldRow}><label>Width (ft)<input name="width" type="number" defaultValue={selectedOpening.width_ft} min=".5" max="12" step=".25" required/></label><label>From wall start (ft)<input name="offset" type="number" defaultValue={ft(selectedOpening.offset_ft)} min="0" max="60" step=".01" required/></label></div><button className={s.secondary}>Apply measurements</button>{selectedOpening.kind==="door"&&<button type="button" className={s.secondary} onClick={()=>patchOpening(selection.index,{swing:((selectedOpening.swing??0)+1)%4})}>Flip hinge / swing ({(selectedOpening.swing??0)+1} of 4)</button>}<button type="button" className={s.textDanger} onClick={()=>{apply({...d,openings:d.openings.filter((_,i)=>i!==selection.index)});setSelection(null);}}>Remove {selectedOpening.kind}</button></form>}
            {d.closed&&!selection&&tool!=="door"&&tool!=="window"&&<div className={s.section}><p className={s.eyebrow}>01 / The room takes shape</p><h2>Now make it yours.</h2><p className={s.muted}>Select a blue corner to reshape the floor. Select a wall to split it. Your next move: add doors and windows.</p><div className={s.buttonRow}><button onClick={()=>chooseTool("door")}>+ Door</button><button onClick={()=>chooseTool("window")}>+ Window</button></div></div>}
            {d.points.length>0&&<details className={s.elements}><summary>Room elements <span>{d.points.length} corners · {d.openings.length} openings</span></summary><ul>{d.points.map((p,i)=><li key={i}><button aria-pressed={selection?.kind==="corner"&&selection.index===i} onClick={()=>{setTool("select");select({kind:"corner",index:i});}}>Corner {i+1}<small>{ft(p.x)}, {ft(p.y)} ft</small></button></li>)}{d.closed&&d.points.map((p,i)=><li key={"wall"+i}><button onClick={()=>{setTool("select");select({kind:"wall",index:i});}}>Wall {i+1}<small>{ft(Math.hypot(d.points[(i+1)%d.points.length].x-p.x,d.points[(i+1)%d.points.length].y-p.y))} ft</small></button></li>)}{d.openings.map((o,i)=><li key={"opening"+i}><button onClick={()=>{setTool("select");select({kind:"opening",index:i});}}>{o.kind==="door"?"Door":"Window"} {i+1}<small>Wall {o.edge+1}</small></button></li>)}</ul></details>}
          </>}
          {tab==="finish"&&<><p className={s.eyebrow}>03 / Set the scene</p><h2>The finishing touches.</h2><label className={s.field}>Ceiling height (ft)<input type="number" min="6" max="16" step=".25" value={d.settings.ceilingFt} onChange={e=>apply({...d,settings:{...d.settings,ceilingFt:Math.max(6,Math.min(16,Number(e.target.value)||6))}})}/></label><fieldset className={s.swatches}><legend>Floor finish</legend>{Object.entries(FLOOR_FINISHES).map(([id,color])=><button key={id} type="button" aria-pressed={d.settings.floor===id} onClick={()=>apply({...d,settings:{...d.settings,floor:id as BuilderDraft["settings"]["floor"]}})}><i style={{background:color}}/>{id}</button>)}</fieldset><label className={s.colorField}>Wall color<input type="color" value={d.settings.wallColor} onChange={e=>apply({...d,settings:{...d.settings,wallColor:e.target.value}})}/></label><label className={s.field}>People sharing this room<select value={d.occupants} onChange={e=>apply({...d,occupants:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n} {n===1?"person":"people"}</option>)}</select></label><label className={s.field}>Mattress size<select value={d.bedSize} onChange={e=>apply({...d,bedSize:e.target.value as BuilderDraft["bedSize"]})}>{BED_SIZES.map(size=><option key={size} value={size}>{size.replace("_"," ").toUpperCase()}</option>)}</select></label><p className={s.fine}>Finishes are a visual preview. Measure the real room and confirm housing rules before buying or installing anything.</p></>}
          <details className={s.options}><summary>Grid &amp; starting over</summary><label className={s.field}>Snap to<select value={snap} onChange={e=>setSnap(Number(e.target.value))}><option value=".25">3 inches</option><option value=".5">6 inches</option><option value="1">1 foot</option></select></label><label className={s.check}><input type="checkbox" checked={cutaway} onChange={e=>setCutaway(e.target.checked)}/>Cut away front walls</label><div className={s.buttonRow}><button onClick={()=>newShape("floor")}>New floor</button><button onClick={()=>newShape("wall")}>Trace new walls</button></div></details>
          {replace&&<div className={s.confirm} role="group" aria-label="Replace room shape"><strong>Start a new room shape?</strong><p>This replaces these walls and openings. Undo brings them back.</p><div className={s.buttonRow}><button onClick={()=>newShape(replace)}>Replace shape</button><button onClick={()=>setReplace(null)}>Keep this room</button></div></div>}
        </div>
        <div className={s.handoff}>{error&&<p className={s.error} role="alert">{error}</p>}<div className={s.roomStats}><span>{d.closed?ft(roomArea(d.points)):"0"}<small>sq ft</small></span><span>{d.closed?d.points.length:Math.max(0,d.points.length-1)}<small>walls</small></span><span>{d.openings.length}<small>openings</small></span></div><button className={s.primary} onClick={finish} disabled={!d.closed||busy}>{busy?"Checking your room…":"Choose style & plan ↗"}</button><p>Your drawn room opens in the <strong>3D planner.</strong></p></div>
      </aside>
    </div>
    <footer className={s.status}><span>{storageNote||"Your room, under construction."}</span><span>{bounds&&d.closed?`${ft(bounds.length)} × ${ft(bounds.width)} ft · `:""}Single-level room · 1 unit = 1 ft</span></footer>
  </div>;
}
function CoordinateForm({title,point,button,onSubmit}:{title:string;point:Point;button:string;onSubmit:(p:Point)=>void}){return <form onSubmit={(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();onSubmit(coordinates(e.currentTarget));}}><h3>{title}</h3><div className={s.fieldRow}><label>X (ft)<input name="x" type="number" min="-30" max="30" step=".01" defaultValue={ft(point.x)} required/></label><label>Z (ft)<input name="y" type="number" min="-30" max="30" step=".01" defaultValue={ft(point.y)} required/></label></div><button className={s.secondary}>{button}</button></form>;}
